let
    Source = Sql.Database("ERINLAPTOP", "AdventureWorks2025"),
    Production_Product = Source{[Schema="Production",Item="Product"]}[Data],
    #"Merged Queries" = Table.NestedJoin(Production_Product, {"ProductSubcategoryID"}, #"Production ProductSubcategory", {"ProductSubcategoryID"}, "Production ProductSubcategory", JoinKind.LeftOuter),
    #"Expanded Production ProductSubcategory" = Table.ExpandTableColumn(#"Merged Queries", "Production ProductSubcategory", {"ProductCategoryID"}, {"Production ProductSubcategory.ProductCategoryID"}),
    #"Merged Queries1" = Table.NestedJoin(#"Expanded Production ProductSubcategory", {"Production ProductSubcategory.ProductCategoryID"}, #"Production ProductCategory", {"ProductCategoryID"}, "Production ProductCategory", JoinKind.LeftOuter),
    #"Reordered Columns" = Table.ReorderColumns(#"Merged Queries1",{"ProductID", "Name", "ProductNumber", "Production ProductCategory", "MakeFlag", "FinishedGoodsFlag", "Color", "SafetyStockLevel", "ReorderPoint", "StandardCost", "ListPrice", "Size", "SizeUnitMeasureCode", "WeightUnitMeasureCode", "Weight", "DaysToManufacture", "ProductLine", "Class", "Style", "ProductSubcategoryID", "ProductModelID", "SellStartDate", "SellEndDate", "DiscontinuedDate", "rowguid", "ModifiedDate", "Production.BillOfMaterials(ProductID)", "Production.BillOfMaterials(ProductID) 2", "Production.ProductCostHistory", "Production.ProductDocument", "Production.ProductInventory", "Production.ProductListPriceHistory", "Production.ProductModel", "Production.ProductProductPhoto", "Production.ProductReview", "Production.ProductSubcategory", "Production.TransactionHistory", "Production.UnitMeasure(SizeUnitMeasureCode)", "Production.UnitMeasure(WeightUnitMeasureCode)", "Production.WorkOrder", "Purchasing.ProductVendor", "Purchasing.PurchaseOrderDetail", "Sales.ShoppingCartItem", "Sales.SpecialOfferProduct", "Production ProductSubcategory.ProductCategoryID"}),
    #"Expanded Production ProductCategory" = Table.ExpandTableColumn(#"Reordered Columns", "Production ProductCategory", {"Name"}, {"Production ProductCategory.Name"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded Production ProductCategory",{"ProductNumber", "MakeFlag", "FinishedGoodsFlag", "Color", "SafetyStockLevel", "ReorderPoint", "Size", "SizeUnitMeasureCode", "WeightUnitMeasureCode", "Weight", "DaysToManufacture", "SellStartDate", "ProductModelID", "SellEndDate", "DiscontinuedDate", "rowguid", "ModifiedDate", "Production.BillOfMaterials(ProductID)", "Production.BillOfMaterials(ProductID) 2"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Production ProductCategory.Name", "Product Category"}, {"Name", "Product Name"}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"Production.WorkOrder", "Purchasing.ProductVendor", "Purchasing.PurchaseOrderDetail", "Sales.ShoppingCartItem", "Sales.SpecialOfferProduct", "Production.UnitMeasure(WeightUnitMeasureCode)", "Production.TransactionHistory"}),
    #"Expanded Production.ProductSubcategory" = Table.ExpandRecordColumn(#"Removed Columns1", "Production.ProductSubcategory", {"Name"}, {"Production.ProductSubcategory.Name"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Production.ProductSubcategory",{{"Production.ProductSubcategory.Name", "Product Subcategory"}}),
    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns1",{"Production.ProductReview", "Production.UnitMeasure(SizeUnitMeasureCode)", "Production ProductSubcategory.ProductCategoryID", "ProductSubcategoryID", "Production.ProductCostHistory", "Production.ProductDocument", "Production.ProductInventory", "Production.ProductListPriceHistory", "Production.ProductModel", "Production.ProductProductPhoto", "ProductLine", "Class", "Style"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns2",{"ProductID", "Product Name", "Product Category", "Product Subcategory", "StandardCost", "ListPrice"})
in
    #"Reordered Columns1"
