let
    Source = Sql.Database("ERINLAPTOP", "AdventureWorks2025"),
    Sales_SalesOrderHeader = Source{[Schema="Sales",Item="SalesOrderHeader"]}[Data],
    #"Removed Columns" = Table.RemoveColumns(Sales_SalesOrderHeader,{"RevisionNumber"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"OrderDate", type date}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type",{"DueDate", "ShipDate"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns1",{{"Status", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","1","In Process",Replacer.ReplaceText,{"Status"}),
    #"Filtered Rows" = Table.SelectRows(#"Replaced Value", each true),
    #"Replaced Value1" = Table.ReplaceValue(#"Filtered Rows","5","Shipped",Replacer.ReplaceText,{"Status"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","2","Approved",Replacer.ReplaceText,{"Status"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","3","Backordered",Replacer.ReplaceText,{"Status"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","4","Rejected",Replacer.ReplaceText,{"Status"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","6","Cancelled",Replacer.ReplaceText,{"Status"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value5",{{"OnlineOrderFlag", type text}}),
    #"Replaced Value6" = Table.ReplaceValue(#"Changed Type2","false","Reseller",Replacer.ReplaceText,{"OnlineOrderFlag"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","True","Online",Replacer.ReplaceText,{"OnlineOrderFlag"}),
    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value7",{{"OnlineOrderFlag", "Sales Channel"}, {"Status", "Order Status"}, {"SalesOrderNumber", "Order Number"}}),
    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns",{"Order Number", "PurchaseOrderNumber", "AccountNumber"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns2",{{"SalesPersonID", "StaffID"}}),
    #"Removed Columns3" = Table.RemoveColumns(#"Renamed Columns1",{"BillToAddressID", "ShipToAddressID", "ShipMethodID", "CreditCardID", "CreditCardApprovalCode", "CurrencyRateID", "Comment", "rowguid", "ModifiedDate", "Person.Address(BillToAddressID)", "Person.Address(ShipToAddressID)", "Purchasing.ShipMethod", "Sales.CreditCard", "Sales.CurrencyRate", "Sales.Customer", "Sales.SalesOrderDetail", "Sales.SalesOrderHeaderSalesReason", "Sales.SalesPerson", "Sales.SalesTerritory"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Columns3", {"TerritoryID"}, #"Sales Geography", {"TerritoryID"}, "Sales Geography", JoinKind.LeftOuter),
    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Merged Queries", {"SalesOrderID", "OrderDate", "Order Status", "Sales Channel", "CustomerID", "StaffID", "TerritoryID", "SubTotal", "TaxAmt", "Freight", "TotalDue"}, "Attribute", "Value"),
    #"Expanded Value" = Table.ExpandTableColumn(#"Unpivoted Columns", "Value", {"Territory"}, {"Value.Territory"}),
    #"Removed Columns4" = Table.RemoveColumns(#"Expanded Value",{"Attribute"}),
    #"Filtered Rows1" = Table.SelectRows(#"Removed Columns4", each [OrderDate] > #date(2022, 6, 30)),
    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows1", {"SalesOrderID"})
in
    #"Removed Duplicates"
